/**
 * Created by ridel1e on 22/10/2016.
 */

export default [
  '<aside class="order-summary">',
    '<header class="order-summary__header">',
      '<span class="order-summary__title" >Order Summary</span>',
      '<a class="order-summary__edit-order-link" href="#">edit order</a>',
    '</header>',
    '<ul class="product-list">',
    '{{#each products}}',
      '<li class="card product">',
        '<img src="{{this.imageUrl}}">',
        '<div class="product__info-block">',
          '<div class="product__name">{{ this.name }}</div>',
          '<div class="product__attributes">{{ this.attributes }}</div>',
          '<div>Quantity: {{ this.quantity }}</div>',
        '</div>',
        '<div class="product__price">${{ this.price }}</div>',
      '</li>',
    '{{/each}}',
    '</ul>',
    '<div class="card order-summary__subtotal-info-container">',
      '<div class="order-summary__info-group">',
        'Subtotal',
        '<span class="order-summary__subtotal-price">${{ subtotalPrice }}</span>',
      '</div>',
      '<div class="order-summary__info-group">',
        'Shipping',
        '<span class="order-summary__shipping-price">',
        '{{#if shippingPrice}}',
          '${{ shippingPrice }}',
        '{{else}}',
          'Free',
        '{{/if}}',
        '</span>',
      '</div>',
      '<div class="order-summary__info-group">',
        'Taxes',
        '<span class="order-summary__taxes">${{ taxes }}</span>',
      '</div>',
    '</div>',
    '<div class="order-summary__info-group order-summary__info-group_name_total-price">',
      'Total',
      '<span class="order-summary__total-price">${{ totalPrice }}</span>',
    '</div>',
  '</aside>'
].join('');